name: CloudFront Deploy
description: Deploy an AWS CloudFront Distribution using Terraform
inputs:
  destroy:
    description: 'Runs Terraform destroy to remove resources created by this action'
    required: false
    default: false
  deploy:
    description: 'Runs Terraform apply to create/update resources created by this action'
    required: false
    default: true
  plan:
    description: 'Runs Terraform plan to check the changes necessary to achieve the desired state'
    required: false
    default: true

  enable_cloudfront:
    description: 'Whether the distribution is enabled to accept end user requests for content'
    required: false
    default: true
  comment:
    description: 'Any comments you want to include about the distribution'
    required: true
  aliases:
    description: 'A comma separated list of extra CNAMEs (alternate domain names). If creating a custom SSL certificate, this list will be used as SANs in the issued certificate'
    required: false
  default_root_object:
    description: 'The object that you want CloudFront to return (for example, index.html) when an end user requests the root URL'
    required: false
  price_class:
    description: 'The price class for this distribution. One of PriceClass_All, PriceClass_200, PriceClass_100'
    required: false
    default: 'PriceClass_100'
  origin_domain_name:
    description: 'The DNS domain name of either the S3 bucket, or web site of your custom origin'
    required: true
  origin_id:
    description: 'A unique identifier for the origin'
    required: true
  origin_path:
    description: 'An optional element that causes CloudFront to request your content from a directory in your Amazon S3 bucket or your custom origin'
    required: false
  allowed_methods:
    description: 'A comma separated list of Controls which HTTP methods CloudFront processes and forwards to your Amazon S3 bucket or your custom origin'
    required: false
    default: 'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'
  cached_methods:
    description: 'Controls whether CloudFront caches the response to requests using the specified HTTP methods'
    required: false
    default: 'GET,HEAD'
  default_ttl:
    description: 'The default amount of time (in seconds) that an object is in a CloudFront cache'
    required: false
    default: 86400
  max_ttl:
    description: 'The maximum amount of time (in seconds) that an object is in a CloudFront cache'
    required: false
    default: 31536000
  min_ttl:
    description: 'The minimum amount of time that you want objects to stay in CloudFront caches'
    required: false
    default: 0
  viewer_protocol_policy:
    description: 'Use this element to specify the protocol that users can use to access the files in the origin. One of allow-all, https-only, or redirect-to-https'
    required: false
    default: 'allow-all'
  forward_headers:
    description: 'Specifies the Headers, if any, that you want CloudFront to vary upon for this cache behavior'
    required: false
  forward_query_string:
    description: 'Indicates whether you want CloudFront to forward query strings to the origin'
    required: false
    default: false
  forward_cookies:
    description: 'Specifies whether you want CloudFront to forward cookies to the origin. You can specify all or none'
    required: false
    default: 'none'

  use_default_cert:
    description: 'If you want viewers to use HTTPS to request your objects and youre using the CloudFront domain name for your distribution'
    required: false
    default: false
  minimum_protocol_version:
    description: 'The minimum version of the SSL protocol that you want CloudFront to use for HTTPS connections'
    required: false
    default: 'TLSv1.2_2018'
  certificate_domain_name:
    description: 'A domain name for which the certificate should be issued'
    required: false
  
  restriction_locations:
    description: 'The ISO 3166-1-alpha-2 codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist)'
    required: false
  locations_restriction_type:
    description: 'The method that you want to use to restrict distribution of your content by country: none, whitelist, or blacklist'
    required: false
    default: 'none'

  logging_bucket:
    description: 'The Amazon S3 bucket to store the access logs in'
    required: false
  logging_include_cookies:
    description: 'Specifies whether you want CloudFront to include cookies in access logs'
    required: false
    default: false
  logging_prefix:
    description: 'An optional string that you want CloudFront to prefix to the access log filenames for this distribution'
    required: false
      

outputs:
  cloudfront_status:
    description: 'The current status of the distribution'
  cloudfront_domain_name:
    description: 'The domain name corresponding to the distribution"'

runs:
  using: docker
  image: Dockerfile
